---
# Create a selfsigned Issuer, in order to create a root CA certificate for RHACM
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-manager-rhacm-selfsign
  namespace: {{ .Release.Namespace | quote }}
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multicloud-ca-cert
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: multicloud-ca-cert
  isCA: true
  issuerRef:
    name: cert-manager-rhacm-selfsign
    kind: Issuer
  commonName: www.redhat.com
  duration: 43800h
  renewBefore: 720h
  organization:
  - "OpenShift ACM"
  keySize: 4096
  dnsNames:
  - www.redhat.com
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: multicloud-ca-issuer
  namespace: {{ .Release.Namespace | quote }}
spec:
  ca:
    secretName: multicloud-ca-cert
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: multicluster-hub-mcm-server-ca-issuer
  namespace: {{ .Release.Namespace | quote }}
spec:
  selfSigned: {}
---
