apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multicloud-ca-cert
  namespace: {{ .Values.pkiNamespace | quote }}
spec:
  secretName: multicloud-ca-cert
  isCA: true
  issuerRef:
    name: cert-manager-rhacm-selfsign
    kind: Issuer
  commonName: www.redhat.com
  duration: 43800h
  renewBefore: 720h
  organization:
  - "OpenShift ACM"
  keySize: 4096
  dnsNames:
  - www.redhat.com
