apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: multicloud-ca-issuer
  namespace: {{ .Values.pkiNamespace | quote }}
spec:
  ca:
    {{ if (lookup "v1" "Secret" .Values.pkiNamespace "byo-ca-cert") }}
    secretName: byo-ca-cert
    {{ else }}
    secretName: multicloud-ca-cert
    {{ end }}
