# Create a selfsigned Issuer, in order to create a root CA certificate for RHACM
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-manager-rhacm-selfsign
  namespace: {{ .Values.pkiNamespace | quote }}
spec:
  selfSigned: {}
