name: cainjector
apiVersion: v1
version: "3.4.0"
appVersion: "0.10.0"
description: A Helm chart for deploying the cert-manager cainjector component
home: https://github.com/jetstack/cert-manager
sources:
  - https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
