name: ibm-cert-manager-webhook
apiVersion: v1
version: 3.5.0
appVersion: 0.10.1
tillerVersion: ">=2.7.0"
kubeVersion: ">=1.9.0-0"
description: A Helm chart for deploying the cert-manager webhook component
home: https://github.com/jetstack/cert-manager
sources:
  - https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
  - Development
  - ICP
  - amd64
  - ppc64le
  - s390x
  - Commercial
  - ICPRHOCP
  - RHOCP
