global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

  # Optional priority class to be used for the cert-manager pods
  priorityClassName: ""
  rbac:
    create: true

replicaCount: 1

strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

podAnnotations: {}

args:
  verbosity: 1

# Optional additional arguments for webhook
extraArgs: []

resources:
  limits:
    memory: "300Mi"
    cpu: "200m"
  requests:
    memory: "150Mi"
    cpu: "100m" 

image:
  repository: ibmcom/icp-cert-manager-webhook
  tag: 0.10.1
  pullPolicy: IfNotPresent

nodeSelector:
  master: "true"

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
# if true, the apiserver's cabundle will be automatically injected into the
# webhook's ValidatingWebhookConfiguration resource by the CA injector.
# in future this will default to false, as the apiserver can use the loopback
# configuration caBundle to talk to itself in kubernetes 1.11+
# see https://github.com/kubernetes/kubernetes/pull/62649
injectAPIServerCA: true

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 10000
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 10000
    privileged: false

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "default"

affinity: {}

watcher:
  optIn: false
  configmap:
    name:
    namespace: 
