name: cert-manager-webhook
apiVersion: v1
version: 3.7.0
appVersion: 0.10.3
tillerVersion: ">=2.7.0"
description: A Helm chart for deploying the cert-manager webhook component
home: https://github.com/jetstack/cert-manager
sources:
  - https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
  - Development
  - amd64
  - ppc64le
  - s390x
  - Commercial
  - RHOCP
