global:
  pullSecret: ""
  imageOverrides:
    cert_manager_webhook: ""
    cert_manager_cainjector: ""
  pullPolicy: Always
  priorityClassName: ""
  rbac:
    create: true
replicaCount: 1
strategy: {}
podAnnotations: {}
args:
  verbosity: 1
extraArgs: []
resources:
  limits:
    memory: 300Mi
    cpu: 200m
  requests:
    memory: 150Mi
    cpu: 100m
tolerations: {}
injectAPIServerCA: true
securityContext:
  pod:
    runAsNonRoot: true
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false
serviceAccount:
  create: false
  name: default
affinity: {}
watcher:
  optIn: true
  configmap:
    name: extension-apiserver-authentication
    namespace: kube-system
pkiNamespace: kube-system
image:
  tag: 3.5.0
